[theme]
background = "#121212"
primary = "light white"
secondary = "light black"
title = "#1ed05e"
playing = "#1ed05e"
playing_bg = "#083012"
highlight = "light white"
highlight_bg = "#484848"
error = "light white"
error_bg = "red"
statusbar = "#202020"
statusbar_progress = "#0ee218"
statusbar_bg = "#118324"
cmdline = "light white"
cmdline_bg = "#121212"
