alias l='ls'
alias la='ls -a'
alias ll='ls -l -h'

alias g='git status -sb'

alias m='time make'

function pingcheck {
    if ping -c 1 -w 1 -W 1 vanenet.hu >& /dev/null; then
        echo "Internet connection is working. :)"
        return 0
    else
        echo "No internet connection. :("
        return 1
    fi
}
alias p='pingcheck'

alias up='sudo apt-get update && sudo apt-get upgrade --yes'

alias vi='vim.tiny -C -u NONE'

alias xb='xboard'
alias xboard='xboard -initialMode Analysis -absoluteAnalysisScores true -scoreWhite true -fUCI -fcp stockfish -sUCI -scp stockfish'

